# fly.toml app configuration file generated for wild-wind-4352 on 2023-06-24T20:57:06+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-wind-4352"
primary_region = "ams"

[http_service]
  internal_port = 7777
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
